version: "3.9"

services:
  mistral-web:
    build: .
    container_name: mistral-web
    runtime: nvidia
    environment:
      - INFER_MODEL=/app/mistral-lora-finetuned
      - HUGGING_FACE_HUB_TOKEN=<HUGGING_FACE_TOKEN>
    ports:
      - "7070:8080"   # host 7070 -> container 8080
    volumes:
      - ./mistral-lora-finetuned:/app/mistral-lora-finetuned
      - ./data:/app/data
      - ./logs:/app/logs
      - ./eval:/app/eval
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
